ProjectManager.MVC/Controllers/ProjectController.cs
using AutoMapper;
using Humanizer.Localisation.DateToOrdinalWords;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using ProjectManager.Application.Project.Commands.CreateProject;
using ProjectManager.Application.Project.Commands.DeleteProject;
using ProjectManager.Application.Project.Commands.EditProject;
using ProjectManager.Application.Project.Queries.GetAllUserProjects;
using ProjectManager.Application.Project.Queries.GetProjectByEncodedName;
using ProjectManager.Application.ProjectRole.Commands.CreateProjectRole;
using ProjectManager.Application.ProjectRole.Commands.RemoveProjectRole;
using ProjectManager.Application.ProjectRole.Queries.GetProjectRoles;
using ProjectManager.Application.ProjectTask.Queries.GetProjectTasks;
using ProjectManager.Application.ProjectTask.Queries.GetUserProjectTasks;
using ProjectManager.MVC.Extensions;
using System.Diagnostics;
using System.Reflection.Metadata.Ecma335;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace ProjectManager.MVC.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public ProjectController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var projectsDto = await _mediator.Send(new GetAllUserProjectsQuery());
            return View(projectsDto);
        }


        [Authorize(Roles = "User, Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateProjectCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }

            await _mediator.Send(command);

            this.SetNotification("success", $"Project {command.Name} successfully created");

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("Project/{projectEncodedName}/Edit")]
        public async Task<IActionResult> Edit(string projectEncodedName)
        {
            var projectDto = await _mediator.Send(new GetProjectByEncodedNameQuery(projectEncodedName));

            if (!projectDto.IsEditable)
            {
                return RedirectToAction("NoAccess", "Home");
            }

            EditProjectCommand project = _mapper.Map<EditProjectCommand>(projectDto);
            return View(project);
        }

        [HttpPost]
        [Route("Project/Edit")]
        public async Task<IActionResult> UpdateProject(EditProjectCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", command);
            }
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("Project/{projectEncodedName}/Details")]
        public async Task<IActionResult> Details(string projectEncodedName)
        {
            var projectDto = await _mediator.Send(new GetProjectByEncodedNameQuery(projectEncodedName));
            return View(projectDto);
        }

        public async Task<IActionResult> Delete(string projectEncodedName)
        {
            await _mediator.Send(new DeleteProjectCommand(projectEncodedName));

            this.SetNotification("error", $"Project {projectEncodedName} has been deleted");

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("Project/{projectEncodedName}/Tasks")]
        public async Task<IActionResult> Tasks(string projectEncodedName)
        {
            var projectDto = await _mediator.Send(new GetProjectByEncodedNameQuery(projectEncodedName));
            return View("Tasks", projectDto);
        }

        [HttpGet]
        [Route("Project/{projectEncodedName}/ProjectRoles")]
        public async Task<IActionResult> ProjectRoles(string projectEncodedName)
        {
            var projectRoles = await _mediator.Send(new GetProjectRolesQuery() { ProjectEncodedName = projectEncodedName});
            return Ok(projectRoles);
        }

        [HttpPost]
        [Route("Project/AddProjectRole")]
        public async Task<IActionResult> AddProjectRole([FromBody] CreateProjectRoleCommand command)
        {
            var result = await _mediator.Send(command);

            if (result.IsSuccess)
            {
                return Ok(result);
            }

            return StatusCode(result.StatusCode, result);
        }

        [HttpPost]
        [Route("Project/RemoveProjectRole")]
        public async Task<IActionResult> RemoveProjectRole([FromBody] RemoveProjectRoleCommand command)
        {
            var result = await _mediator.Send(command);

            if (result.IsSuccess)
            {
                return Ok(result);
            }

            return StatusCode(result.StatusCode, result);
        }
    }
}

ProjectManager.MVC/Controllers/ProjectTaskController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Application.Project.Queries.GetProjectByEncodedName;
using ProjectManager.Application.Project.Queries.GetProjectEncodedNameByTaskId;
using ProjectManager.Application.ProjectContributors.Queries.GetAllProjectContributors;
using ProjectManager.Application.ProjectTask.Commands.AddComment;
using ProjectManager.Application.ProjectTask.Commands.CreateProjectTask;
using ProjectManager.Application.ProjectTask.Commands.DeleteProjectTask;
using ProjectManager.Application.ProjectTask.Commands.EditProjectTask;
using ProjectManager.Application.ProjectTask.Commands.DeleteCommand;
using ProjectManager.Application.ProjectTask.Queries.GetProjectTaskById;
using ProjectManager.Application.ProjectTask.Queries.GetProjectTasks;
using ProjectManager.Application.ProjectTask.Queries.GetUserProjectTasks;
using ProjectManager.MVC.Extensions;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
using ProjectManager.Application.ProjectTask.Commands.LogTime;
using ProjectManager.Application.ProjectTask.Commands.DeleteLogTime;

namespace ProjectManager.MVC.Controllers
{
    public class ProjectTaskController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public ProjectTaskController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        [HttpPost]
        [Authorize]
        [Route("Project/Tasks/Create")]
        public async Task<IActionResult> CreateProjectTask(CreateProjectTaskCommand command)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            await _mediator.Send(command);

            return Ok();
        }

        [Route("Project/{projectEncodedName}/ProjectTask/{taskId}/Edit")]
        public async Task<IActionResult> EditProjectTask(string projectEncodedName, int taskId, bool isEditable)
        {
            var task = await _mediator.Send(new GetProjectTaskByIdQuery(taskId));
            var projectContributors = await _mediator.Send(new GetAllProjectContributorsQuery(projectEncodedName));
            var command = new EditProjectTaskCommand
            {
                Id = task.Id,
                Name = task.Name,
                Description = task.Description,
                TaskProgressStatus = task.TaskProgressStatus,
                AssignedUserEmail = task.AssignedUserEmail,
                Deadline = task.Deadline,
                ProjectContributors = projectContributors,
                IsEditable = isEditable
            };
            return View("EditProjectTask", command);
            
        }

        [HttpPost]
        [Route("ProjectTask/UpdateProjectTask")]
        public async Task<IActionResult> UpdateProjectTask(EditProjectTaskCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View("EditProjectTask", command);
            }
            await _mediator.Send(command);
            this.SetNotification("success", $"Task edited");
            var projectEncodedName = await _mediator.Send(new GetProjectEncodedNameByTaskIdQuery(command.Id));
            return RedirectToAction("Details", new { projectEncodedName = projectEncodedName, taskId = command.Id, isEditable = command.IsEditable });
        }

        [HttpGet]
        [Route("Project/{projectEncodedName}/Tasks/{taskId}/Details")]
        public async Task<IActionResult> Details(int taskId, string projectEncodedName, bool isEditable)
        {
            var task = await _mediator.Send(new GetProjectTaskByIdQuery(taskId));            

            ViewData["ProjectEncodedName"] = projectEncodedName;
            ViewData["IsEditable"] = isEditable;

            return View(task);
        }

        [HttpPost]
        [Route("ProjectTask/{id}/Delete")]
        public async Task<IActionResult> DeleteTask([FromRoute]int id)
        {
            DeleteProjectTaskCommand command = new DeleteProjectTaskCommand { Id = id };
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            await _mediator.Send(command);

            return Ok();
        }

        [HttpGet]
        [Route("Project/{projectEncodedName}/Tasks/GetTasks")]
        public async Task<IActionResult> GetProjectTasks(string projectEncodedName)
        {
            var data = await _mediator.Send(new GetProjectTasksQuery() { ProjectEncodedName = projectEncodedName });
            return Ok(data);
        }

        [HttpGet]
        [Route("Project/{projectEncodedName}/Tasks/GetTasks/{userEmail}")]
        public async Task<IActionResult> GetUserProjectTasks(string projectEncodedName, string userEmail)
        {
            var data = await _mediator.Send(new GetUserProjectTasksQuery() { ProjectEncodedName = projectEncodedName, UserEmail = userEmail });
            return Ok(data);
        }

        [HttpPost]
        public async Task<IActionResult> AddComment([FromBody]AddCommentCommand command)
        {
            var result = await _mediator.Send(command);
            if (result.IsSuccess)
            {
                return Ok(result);
            }

            return StatusCode(result.StatusCode, result);
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteEntity(int entityId, string entityType)
        {
            Application.Common.CommandResult result;
            if (entityType == "comment")
            {
                result = await _mediator.Send(new DeleteComentCommand() { CommentId = entityId });
            } else if (entityType == "logtime")
            {
                result = await _mediator.Send(new DeleteLogTimeCommand() { LogTimeId = entityId });
            } else
            {
                return BadRequest("Invalid entity type");
            }
            return result.IsSuccess ? Ok(result) : StatusCode(result.StatusCode, result);
        }

        [HttpPost]
        public async Task<IActionResult> LogTime([FromBody]LogTimeCommand command)
        {
            var result = await _mediator.Send(command);
            if (result.IsSuccess)
            {
                return Ok(result);
            }

            return StatusCode(result.StatusCode, result);
        }
    }
}

ProjectManager.MVC/Views/ProjectTask/Details.cshtml
@model ProjectManager.Application.ProjectTask.ProjectTaskDto
@using Microsoft.AspNetCore.Identity
@inject UserManager<ProjectManager.Domain.Entities.User> UserManager

@{
    ViewData["Title"] = "Task Details";
    var projectEncodedName = ViewData["ProjectEncodedName"]?.ToString() ?? string.Empty;
    bool isEditable = ViewData["IsEditable"] as bool? ?? false;
    var user = await UserManager.GetUserAsync(User);
    bool isAdmin = await UserManager.IsInRoleAsync(user, "Admin");
    var userEmail = user?.Email;
}

<div class="container mt-5">
    <div class="card shadow-lg border-0">
        <div class="card-header bg-primary text-white">
            <h3 class="mb-0 d-flex justify-content-between align-items-center">
                <span>@Model.Name</span>
                <span class="badge bg-light text-dark">@Model.TaskProgressStatus</span>
            </h3>
        </div>
        <div class="card-body">
            <div class="mb-3">
                <h5 class="card-title">Assigned User</h5>
                <p class="card-text">@(!string.IsNullOrEmpty(Model.AssignedUserEmail) ? Model.AssignedUserEmail : "Unassigned")</p>
            </div>
            <div class="mb-3">
                <h5 class="card-title">Description</h5>
                <p style="white-space: pre-wrap;" class="card-text">@(!string.IsNullOrWhiteSpace(Model.Description) ? Model.Description : "No description provided")</p>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <h5 class="card-title">Deadline</h5>
                    <p class="card-text">@Model.Deadline.ToString("dd-MM-yyyy HH:mm")</p>
                </div>
                <div class="col-md-4">
                    <h5 class="card-title">Assignment Time</h5>
                    <p class="card-text">@Model.AssignmentTime.ToString("dd-MM-yyyy HH:mm")</p>
                </div>
                <div class="col-md-4">
                    <h5 class="card-title">Time Spent</h5>
                    <p class="card-text">@Model.TaskComments.Where(tc => tc.IsLogTime == true).Sum(tc => tc.TimeSpent.Value.TotalHours) hours</p>
                </div>
            </div>
        </div>
        <div class="card-footer d-flex justify-content-between">
            @if (isEditable)
            {
                <a asp-controller="ProjectTask" asp-action="EditProjectTask" asp-route-taskId="@Model.Id" asp-route-projectEncodedName="@projectEncodedName" asp-route-isEditable="@isEditable" class="btn btn-primary">
                    <i class="bi bi-pencil"></i> Edit
                </a>
            }

            <a asp-action="Tasks" asp-controller="Project" asp-route-projectEncodedName="@projectEncodedName" class="btn btn-secondary">
                <i class="bi bi-arrow-left"></i> Back to Tasks
            </a>
        </div>
    </div>

    <div class="card mt-4">
        <div id="logTime" class="card-body">
            <h5 class="mb-3">Log Time</h5>
            <button id="showLogTimeForm" class="btn btn-outline-primary mb-3">
                <i class="bi bi-clock"></i> Log Time
            </button>

            <form id="logTimeForm" class="mt-3 d-none">
                <div class="form-group">
                    <label for="commitMessage">Commit Message</label>
                    <input type="text" id="commitMessage" name="CommitMessage" class="form-control" placeholder="Enter commit message" required>
                </div>
                <div class="form-group mt-3">
                    <label for="timeSpent">Time Spent (in hours)</label>
                    <input type="number" id="timeSpent" name="TimeSpent" class="form-control" placeholder="Enter time in hours" min="0.1" step="0.1" required>
                </div>
                <input type="hidden" name="TaskId" value="@Model.Id">
                <input type="hidden" name="UserId" value="@user?.Id">
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
            </form>
        </div>
    </div>

    <div class="card mt-4">
        <div id="comments" class="card-body">
            <h5 class="mb-3">Comments</h5>
            <ul class="list-group">
                @foreach (var comment in Model.TaskComments)
                {
                    <li class="list-group-item d-flex justify-content-between align-items-start @(comment.IsLogTime ? "bg-light" : "bg-white")">
                        <div class="d-flex flex-column">
                            @if (comment.IsLogTime)
                            {
                                <p>
                                    <strong>@comment.CreatedByEmail</strong> logged time <strong>@comment.TimeSpent</strong> at
                                    <span class="text-muted">(@comment.CreatedAt.ToString("dd-MM-yyyy HH:mm"))</span>
                                </p>
                                <p class="mb-0">@comment.Message</p>
                            }
                            else
                            {
                                <strong>@comment.CreatedByEmail</strong>
                                <span class="text-muted">(@comment.CreatedAt.ToString("dd-MM-yyyy HH:mm"))</span>
                                <p class="mb-0">@comment.Message</p>
                            }
                        </div>

                        @if (comment.CreatedByEmail == userEmail || isAdmin)
                        {
                            <button class="btn btn-outline-danger btn-sm ms-3 delete-comment-button" type="@(@comment.IsLogTime ? "logTime" : "comment")" data-commentId="@comment.Id">
                                <i class="bi bi-trash"></i> Delete
                            </button>
                        }
                    </li>
                }
            </ul>

            <form id="addCommentForm" class="mt-3">
                <div id="newComment" class="form-group">
                    <label for="newComment">Add a Comment</label>
                    <textarea id="newComment" name="Comment" class="form-control" rows="3" required></textarea>
                </div>
                <input type="hidden" name="TaskId" value="@Model.Id" />
                <input type="hidden" name="UserId" value="@user?.Id" />
                <input type="submit" class="btn btn-primary mt-2 submit-new-comment" value="Submit">
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/Project/CommentManagment.js"></script>
    <script src="~/js/Project/TimeLogManagment.js"></script>
    <script>
        const projectEncodedName = "@projectEncodedName";
        const taskId = @Model.Id;
        const isEditable = "@isEditable";
    </script>
}

ProjectManager.MVC/Views/ProjectTask/EditProjectTask.cshtml
@model ProjectManager.Application.ProjectTask.Commands.EditProjectTask.EditProjectTaskCommand

@{
    ViewData["Title"] = "EditProjectTask";
}

<div class="text-center">
    <h1>@Model.Name</h1>

    <h4>Edit Task Details</h4>
</div>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-controller="ProjectTask" asp-action="UpdateProjectTask">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <input asp-for="Id" class="form-control" type="hidden"/>
            <input asp-for="ProjectContributors" class="form-control" type="hidden"/>
            <input asp-for="IsEditable" class="form-control" type="hidden" />

                
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskProgressStatus" class="control-label">Status</label>
                <select asp-for="TaskProgressStatus" class="form-control">
                    <option value="NotAssigned">Not Assigned</option>
                    <option value="InProgress">In Progress</option>
                    <option value="Completed">Completed</option>
                </select>
                <span asp-validation-for="TaskProgressStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignedUserEmail" class="control-label">Assigned User Email</label>
                <select asp-for="AssignedUserEmail" class="form-control">
                    <option value="Unassigned">Unassigned</option>
                    @foreach(var projectUser in Model.ProjectContributors)
                    {
                        <option value="@projectUser.Email">@projectUser.Email</option>
                    }
                </select>
                <span asp-validation-for="TaskProgressStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group text-center m-4">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectManager.MVC/Views/ProjectTask/_CreateProjectTask.cshtml
@model ProjectManager.Application.ProjectTask.Commands.CreateProjectTask.CreateProjectTaskCommand

<!-- Button trigger modal -->
<div class="text-center">
    <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#createProjectTaskServiceModal">
        Add Task
    </button>
</div>
<!-- Modal -->
<div class="modal fade" id="createProjectTaskServiceModal" tabindex="-1" aria-labelledby="createProjectTaskServiceModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-controller="ProjectTask" asp-action="CreateProjectTask">

                <div class="modal-header">
                    <h5 class="modal-title" id="createProjectTaskServiceModalLabel">New Project Task</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input asp-for="ProjectEncodedName" class="form-control" type="hidden" />

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control text-center" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control text-center" rows="4"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TaskProgressStatus" class="control-label">Status</label>
                        <select asp-for="TaskProgressStatus" class="form-control text-center">
                            <option value="NotAssigned">Not Assigned</option>
                            <option value="InProgress">In Progress</option>
                            <option value="Completed">Completed</option>
                        </select>
                        <span asp-validation-for="TaskProgressStatus" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AssignedUserEmail" class="control-label">Assign to</label>
                        <select asp-for="AssignedUserEmail" class="form-control text-center">
                            <option value="">-- Loading contributors... --</option>
                        </select>
                        <span asp-validation-for="AssignedUserEmail" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Deadline" class="control-label"></label>
                        <input asp-for="Deadline" class="form-control text-center" type="datetime-local" value="">
                        <span asp-validation-for="Deadline" class="text-danger"></span>
                    </div>

                    

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input type="submit" value="Create" class="btn btn-primary">
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}